services:
  - type: web
    name: diabetes-prediction-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app/app.py --server.port $PORT --server.enableCORS false

