services:
  - name: diabetes-app
    startCommand: streamlit run app/app.py --server.port 8000 --server.enableCORS false --server.address 0.0.0.0
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
    autoDeploy: true

